### ISSUE TITLE
Use env to resolve labels

### ISSUE THREAD

**Issue by miton18** [ovh/beamium#118]
My dream:

use an env var to replace labels values

```yaml
...
labels:
  my_label: "env:ENV_VAR"
...
```
