### ISSUE TITLE
Fetch metrics on scraper protected by Basic auth

### ISSUE THREAD

**Issue by babolivier** [ovh/beamium#52]
One of my data sources protects its endpoints with Basic auth, rendering beamium unable to fetch metrics from it (using version `1.7.0-jessie` from the deb repository). It would be very helpful if Basic auth could be supported in beamium.

**Comment by ziirish** [comment]
That's funny, I was just looking into this feature as well.

I'm working on a patch that will hopefully enable the use of custom headers while scrapping the sources.

Example:

```
scappers:
  scrapper1:
    url: http://127.0.0.1:9100/metrics
    format: sensision
    period: 10000
    headers:
      Authorization: Basic XXXXX==
```
