### ISSUE TITLE
Move files that cannot be sent into another folder

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [ovh/beamium#61]
Hello!

A feature which can be useful is to move files that have errors into another folder in order to avoid beamium loop on those files.

It could be something like this in settings:

```yml
parameters:             # Parameters definitions                        (Optional)
  source-dir: sources   # Beamer data source directory                  (Optional, default: sources)
  sink-dir: sinks       # Beamer data sink directory                    (Optional, default: sinks)
  error-dir: errors     # Folder to puts files with errors              (Optional, default: puts file at the same place) 
  scan-period: 1000     # Delay(ms) between source/sink scan            (Optional, default: 1000)
  batch-count: 250      # Maximum number of files to process in a batch (Optional, default: 250)
  batch-size: 200000    # Maximum batch size                            (Optional, default: 250)
  log-file: beamium.log # Log file                                      (Optional, default: beamium.log)
  log-level: 4          # Log level                                     (Optional, default: info)
  timeout: 500          # Http timeout (seconds)                        (Optional, default: 500)
```

Thanks in advance.
