### ISSUE TITLE
Handle units in settings

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [ovh/beamium#63]
Hi!

An awesome feature for beamium which to set preferences in configuration file using unit in addition of actual bit. 

We could have something like this:

- `T`: for tera bytes
- `G`: for giga bytes
- `M`: for mega bytes
- `K`: for kilo bytes

An example of configuration using this feature could be:

```yml
parameters:             # Parameters definitions                        (Optional)
  source-dir: sources   # Beamer data source directory                  (Optional, default: sources)
  sink-dir: sinks       # Beamer data sink directory                    (Optional, default: sinks)
  error-dir: errors     # Folder to puts files with errors              (Optional, default: puts file at the same place) 
  scan-period: 1000     # Delay(ms) between source/sink scan            (Optional, default: 1000)
  batch-count: 250      # Maximum number of files to process in a batch (Optional, default: 250)
  batch-size: 200000    # Maximum batch size                            (Optional, default: 250)
  log-file: beamium.log # Log file                                      (Optional, default: beamium.log)
  log-level: 4          # Log level                                     (Optional, default: info)
  size: 350G            # Remove the oldest files in folder if disk is over 350 giga bytes
  timeout: 500          # Http timeout (seconds)                        (Optional, default: 500)
```
