### ISSUE TITLE
beamium doesn't append scraper-specific labels

### ISSUE THREAD

**Issue by babolivier** [ovh/beamium#72]
Part of our scrapers config looks like this:

```
  exporter:
    url: http://exporter:9238/metrics
    period: 60000
    format: prometheus
    labels:
      cluster: cluster1
```

Because not all nodes belong to the same cluster, we specify their cluster in a label because that way we can easily distinguish a cluster from another in Warp10. However, none of the metrics sent to Warp10 contain the `cluster` label.
