### ISSUE TITLE
issue with label on scrapper 

### ISSUE THREAD

**Issue by yesnault** [ovh/beamium#92]
with this conf:

```yml
          sinks:
            warp10:
              url: https://xxxxxx
              token-header: X-Warp10-Token
              token: '{{ warp10Token }}'
          scrapers:
            scraper_localhost:
              url: http://127.0.0.1:9100/metrics
              period: 60000
              format: sensision
              labels:
                instance: foo
```
-> label 'instance' is not sent
